name: Monitoreo

on:
  push:
    paths:
      - 'monitoring/**' 
jobs:
  deploy-monitoring:
    runs-on: ubuntu-latest

    steps:
    - name: SSH into EC2 and deploy monitoring services
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          script: |
            cd /home/ec2-user/taller3
            git pull origin main
             docker compose pull      # Si usas imágenes desde GHCR
             docker compose up -d     # Levanta TODOS los servicios
             docker ps

